spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/middleearth
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: MESBG-Buddy_Backend
